### PR TITLE
Replace deprecated spin_until_future_complete with spin_until_complete

### PR DESCRIPTION
**Pull request by hliberacki**
Signed-off-by: Hubert Liberacki <hliberacki@gmail.com>

### CODE REVIEW

**Comment by hliberacki** [comment]
Due to change in RCLCPP - https://github.com/ros2/rclcpp/pull/1874 Pull request

**Review by fujitatomoya — CHANGES_REQUESTED** [review]
Can we avoid unnecessary changes to re-format?

**Comment by hliberacki** [comment]
@fujitatomoya i will restore all formating base changes, they were due to some formatting plugin in IDE which did it implicitly (i did not check the diff good enough). it was not my intention

**Review by jacobperron — COMMENTED** [review]
For context, this connects to https://github.com/ros2/rclpy/pull/919

**Review by hidmic — APPROVED** [review]
LGTM with passing CI

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16514/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11102/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16886/)

**Comment by hidmic** [comment]
@ros-pull-request-builder retest this please

**Comment by hliberacki** [comment]
> LGTM with passing CI
>

Unfortunately, this CI will most probably fail. This is because it did not include all the related PRs and there will be a missing include issue. Here is a CI run for all my changes in each connected PRs.

https://github.com/ros2/rclcpp/pull/1874#issuecomment-1086906375

**Comment by hidmic** [comment]
@hliberacki thanks for the heads up.

Indeed, CI will fail w/o https://github.com/ros2/rclpy/pull/919.

**Comment by wjwwood** [comment]
Since this is part of rclpy changes, it's blocked on https://github.com/ros2/rclpy/pull/919#pullrequestreview-1018757431, but is not needed to fix CI after https://github.com/ros2/rclcpp/pull/1874 was merged prematurely.

**Review by SteveMacenski — APPROVED** [review]

**Comment by christophebedard** [comment]
I've opened #396 to replace this PR.

**Comment by christophebedard** [comment]
This can be closed, see https://github.com/ros2/launch_ros/pull/396#issuecomment-2035715945

**Pull request closed without merging**
