### PR TITLE
[Backport] Make launch_testing_ros examples more robust. (#394)

### PR DESCRIPTION
**Pull request by fujitatomoya**
closes https://github.com/ros2/launch_ros/issues/408

> [!NOTE]  
> backport to humble

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
git detected some conflict because of the base code difference from https://github.com/ros2/launch_ros/pull/394, all conflicts are resolved.

**Comment by fujitatomoya** [comment]
Pulls: ros2/launch_ros#420
Gist: https://gist.githubusercontent.com/fujitatomoya/3da9f1735544bfe657d221ac299b8f32/raw/2007a7866390475ce2528493cd3524409141f917/ros2.repos
BUILD args:  --packages-up-to launch_testing_ros
TEST args:  --packages-select launch_testing_ros
ROS Distro: iron
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14706
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21998/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16259/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1511/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22731/)

**Comment by Blast545** [comment]
Just retriggered your CI launcher, parameters lgtm, it seems it failed for infra reasons:

https://ci.ros2.org/job/ci_launcher/14709/
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22001/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16262/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1514/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22734/)

**Comment by fujitatomoya** [comment]
@Blast545 i think i messed up something during resolving conflicts, let me get back to you. if you want to skip the test to avoid backporting, that is also fine to me!

**Comment by clalancette** [comment]
> @Blast545 i think i messed up something during resolving conflicts, let me get back to you. if you want to skip the test to avoid backporting, that is also fine to me!

I just ended up pushing [78a38fa](https://github.com/ros2/launch_ros/pull/420/commits/78a38fa0c1d0adae39ec71934db3cee908478631), which removes the type hints (which don't work on Iron).  That makes it pass my tests locally.  I'll rerun CI here.

**Comment by clalancette** [comment]
There are two warnings on RHEL, but they are unrelated to this PR.  I'm going to go ahead and approve and merge this.

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
@Mergifyio backport humble

**Pull request merged**
