### PR TITLE
Foxy: Simplify logic for mode switch

### LINKED ISSUE #221: [ros2launch] [cli] ros2 launch fails with absolute path and argument
## Bug report

**Required Info:**

- Operating System:
ros:foxy docker image on Ubuntu 18.04 (Likely affects all)
- Installation type:
binary in docker image (Likely affects all)
- Version or commit hash:
Version reported in ros2launch package.xml is 0.11.1
- DDS implementation:
Whichever is default in docker image (Likely affects all)
- Client library (if applicable):
Not applicable to issue

##### Setup
Spawn a container and enter shell:
```
docker run -it ros:foxy bash
```
In the image, install demo_nodes_cpp to provide a target launch file:
```
apt update && apt install ros-foxy-demo-nodes-cpp
```

##### Issue causing variant
Test absolute `'single file'` launching variant with argument:
```
ros2 launch /opt/ros/foxy/share/demo_nodes_cpp/launch/services/add_two_ints_async.launch.py example_arg:="foobar"
```

##### Functional variants
Test `'pkg file'` launching variant:
```
ros2 launch demo_nodes_cpp add_two_ints_async.launch.py
```
Test `'pkg file'` launching variant, with argument:
```
ros2 launch demo_nodes_cpp add_two_ints_async.launch.py example_arg:="foobar"
```
Test absolute `'single file'` launching variant:
```
ros2 launch /opt/ros/foxy/share/demo_nodes_cpp/launch/services/add_two_ints_async.launch.py
```

#### Expected behavior

Successfully runs the launch file for all variants.

#### Actual behavior

Absolute `'single file'` with argument fails with error:
```
file 'example_arg:=foobar' was not found in the share directory of package '/opt/ros/foxy/share/demo_nodes_cpp/launch/services/add_two_ints_async.launch.py' which is at '/opt/ros/foxy/share/demo_nodes_cpp/launch/services/add_two_ints_async.launch.py'
```

#### Additional information

This is due to behaviour of `ament_index_python` when passed an absolute path, see [PR#69 on ament_index](https://github.com/ament/ament_index/pull/69) for more details. In brief, if a valid absolute path was passed to `get_package_prefix()` as the package name, a `PackageNotFoundError` was __not__ raised.

I had begun to put together a fix for this but got lost trying to implement a set of tests for the CLI. Lack of CLI tests is potentially worthy of a separate issue.

### PR DESCRIPTION
**Pull request by rob-clarke**
Backport of #230 for foxy
Fixes #221

### CODE REVIEW

**Comment by jacobperron** [comment]
Do we need https://github.com/ament/ament_index/pull/69 in Foxy for this change to work?

**Comment by rob-clarke** [comment]
No, this is a workaround for the `get_package_prefix` function so doesn't need the ament_index patch.

**Comment by jacobperron** [comment]
@ros-pull-request-builder retest this please

**Review by jacobperron — APPROVED** [review]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15331/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10042/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13011/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15524/)

**Pull request merged**
