### PR TITLE
Add async support for subscribing messages

### PR DESCRIPTION
**Pull request by Ryanf55**
This is an alternative to #356, used for discussion. It doesn't pass because the wait blocks.

### CODE REVIEW

**Comment by Ryanf55** [comment]
@LastStarDust  FYI, here is another approach without using callbacks. Note how I also create a publisher in the test python code rather than calling the CI, which is more conducive to an application where you want to set specific fields in the test.

**Comment by Ryanf55** [comment]
> @Ryanf55 Thank you for letting me know. I have some comments about the code, but before I invest any time in this I want to hear the opinion of the maintainers.

Looks like there are not really any active maintainers who have time to discuss this support. Are you still interested in getting better subscriber testing on `humble`?

**Comment by LastStarDust** [comment]
@Ryanf55 for sure I am still interested in getter better subscriber testing on `humble`. 

@project owners
If there are no active maintainers or if they have no time for this feature, would you let us take care of this? In other words, would you give @Ryanf55 and @LastStarDust temporary maintainer role?

**Comment by LastStarDust** [comment]
> > If there are no active maintainers or if they have no time for this feature, would you let us take care of this? In other words, would you give @Ryanf55 and @LastStarDust temporary maintainer role?
> 
> There are active maintainers of this repository. In general, this is very core ROS 2 stuff, so I don't think giving temporary maintainer role is suitable here.
> 
> That said, at the very least a new feature needs to target `rolling` first. Once this is targeted at `rolling`, I'll try to get a maintainer to look at it.

Fair enough. BTW [my PR](https://github.com/ros2/launch_ros/pull/356) is already targeting `rolling`.

**Pull request closed without merging**
