### PR TITLE
Fix linter by removing unused import

### PR DESCRIPTION
**Pull request by emersonknapp**
Linter error showing up in all nightly builds

### CODE REVIEW

**Comment by emersonknapp** [comment]
@ros2/aws-oncall - please run this CI job
Gist: https://gist.githubusercontent.com/emersonknapp/d14101755c970057ab0cfee2f450e3e4/raw/9a437423ecc8cb69048889e86cf125f95718c14f/ros2.repos
BUILD args: --packages-up-to launch_ros
TEST args: --packages-select launch_ros
Job: ci_launcher

**Comment by emersonknapp** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8950/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4718/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7320/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8859/)

**Comment by dirk-thomas** [comment]
The fix needs to be backported to Eloquent: http://build.ros2.org/view/Eci/job/Eci__nightly-fastrtps_ubuntu_bionic_amd64/216/testReport/

**Comment by zmichaels11** [comment]
Backported to Eloquent with PR #117

**Pull request merged**
