### PR TITLE
Clean up several pytest warnings

### PR DESCRIPTION
**Pull request by mjcarroll**
I found several easily-addressed warnings when debugging another issue.

Signed-off-by: Michael Carroll <michael@openrobotics.org>

### CODE REVIEW

**Comment by mjcarroll** [comment]
Before: [Build Status](https://ci.ros2.org/job/ci_linux/10274/)

After: 
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10275/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5812/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8357/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10172/)

**Comment by mjcarroll** [comment]
Note to reviewers that you'll have to actually look at the console results, since those warnings currently aren't surfaced.

**Comment by mjcarroll** [comment]
Probably should have tested on `focal` first, looking into the new failure.

**Comment by hidmic** [comment]
@mjcarroll do we want this in Foxy?

**Comment by mjcarroll** [comment]
@hidmic Yes, I just recently installed focal on my laptop and don't have much bandwidth for ROS2 at the moment.  I'll try to get a look at it today.

**Comment by jacobperron** [comment]
Here's a more recent build on Focal: [Build Status](https://ci.ros2.org/job/ci_linux/10735/)

**Comment by mjcarroll** [comment]
@ros-pull-request-builder retest this please

**Pull request merged**
