### PR TITLE
Asynchronously wait for load node service response

### LINKED ISSUE #171: LoadComposableNodes action can cause launch process to hang forever
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - Any
- Version or commit hash:
  - Any
- DDS implementation:
  - N/A
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

Run this broken mock node component container:

```python
import time
import threading

from composition_interfaces.srv import LoadNode
import rclpy
import rclpy.context
import rclpy.executors
import rclpy.node


class MockComponentContainer(rclpy.node.Node):

    def __init__(self):
        # List of LoadNode requests received
        self.requests = []

        self._context = rclpy.context.Context()
        rclpy.init(context=self._context)

        super().__init__('mock_component_container', context=self._context)

        self.load_node_service = self.create_service(LoadNode, '~/_container/load_node', self.load_node_callback)

        self._executor = rclpy.executors.SingleThreadedExecutor(context=self._context)

        # Start spinning in a thread
        self._thread = threading.Thread(target=rclpy.spin, args=(self, self._executor), daemon=True)
        self._thread.start()

    def load_node_callback(self, request, response):
        print(f'Request received: {request}')
        self.requests.append(request)
        response.success = True
        response.full_node_name = f'{request.node_namespace}/{request.node_name}'
        response.unique_id = len(self.requests)
        # BROKEN HERE (forgot to return response)

    def ok(self):
        return rclpy.ok(context=self._context)


def main():
    container = MockComponentContainer()
    while container.ok():
        time.sleep(1)


if __name__ == '__main__':
    main()
```

Launch a LoadComposableNodes action pointing to the broken container:

```
import launch

from launch_ros.actions import LoadComposableNodes
from launch_ros.descriptions import ComposableNode


def generate_launch_description():
    return launch.LaunchDescription([
        LoadComposableNodes(
            target_container='/mock_component_container',
            composable_node_descriptions=[
                ComposableNode(
                    package='demo_nodes_cpp',
                    plugin='demo_nodes_cpp::Talker',
                )
            ]
        )
    ])
```

#### Expected behavior

LoadComposableNodes action fails to load the node gracefully.

#### Actual behavior

The launch process hangs forever. Even trying to send sigint or sigquit fails. We need to sigkill the launch process.

#### Additional information

After some debugging, it appears that we get stuck in this synchronous service call:

https://github.com/ros2/launch_ros/blob/91097d16e059f78fb9af511fd8ebee74af213e86/launch_ros/launch_ros/actions/load_composable_nodes.py#L103

And so the future being tracked by the launch context is never completed and launch waits indefinitely.

Perhaps there are two bugs here,

1. Launch should probably not wait indefinitely for all futures to complete during shutdown. Rather, it should probably timeout and cancel these hung futures.
2. We can fix the LoadComposableNodes action so that makes an asynchronous service call and monitors the launch shutdown state (similar to the [LifecycleNode action](https://github.com/ros2/launch_ros/blob/91097d16e059f78fb9af511fd8ebee74af213e86/launch_ros/launch_ros/actions/lifecycle_node.py#L116-L132)) .

### PR DESCRIPTION
**Pull request by jacobperron**
Fixes #171

By asychronously waiting for the service response, we can monitor if launch is shutting down and abandon the request so we don't block the shutdown process.

### CODE REVIEW

**Comment by jacobperron** [comment]
Maybe there's a better way, but I just copied the logic from the LifecycleNode action. If we come up with something better, we can refactor both.

**Comment by jacobperron** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12106/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7108/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9858/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12015/)

**Comment by adamdbrw** [comment]
Is there a plan to backport this to Foxy? It is a real issue for some users. Is there anything I can do to help? @jacobperron @clalancette

**Comment by jacobperron** [comment]
@adamdbrw Thanks for the ping. I think I was planning to backport this (along with other changes) to Foxy, but it got a bit gnarly with Git conflicts. I'm happy to review a backport PR if you'd like to open one. Keep in mind that we should stay API compatible.

**Comment by adamdbrw** [comment]
@jacobperron for me this patch applied on Foxy without conflicts. Perhaps after several backport the problem is solved already?

**Comment by jacobperron** [comment]
@adamdbrw That's quite possible :slightly_smiling_face:

**Comment by jacobperron** [comment]
Foxy backport: https://github.com/ros2/launch_ros/pull/240

**Pull request merged**
