### PR TITLE
Use sets of file extensions provided by parser extensions

### PR DESCRIPTION
**Pull request by christophebedard**
Requires https://github.com/ros2/launch/pull/516

Signed-off-by: Christophe Bedard <bedard.christophe@gmail.com>

### CODE REVIEW

**Comment by christophebedard** [comment]
CI `--packages-above launch_ros test_launch_ros`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14844/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9594/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12511/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15003/)

I should run CI for both this PR and https://github.com/ros2/launch/pull/516, but I forgot.

**Review by hidmic — APPROVED** [review]
LGTM pending green CI

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14871/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9621/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12538/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15030/)

**Comment by christophebedard** [comment]
@hidmic should `launch` be released (with https://github.com/ros2/launch/pull/516) before this is merged?

**Comment by hidmic** [comment]
@christophebedard indeed. I'll do that tomorrow morning first thing.

**Comment by christophebedard** [comment]
@ros-pull-request-builder retest this please

**Comment by clalancette** [comment]
@ros-pull-request-builder retest this please

**Comment by hidmic** [comment]
Alright, all jobs are green. Going in !

**Pull request merged**
