### PR TITLE
RosTimer -> ROSTimer and PushRosNamespace -> PushROSNamespace, to follow PEP8

### PR DESCRIPTION
**Pull request by wjwwood**
Follow up of https://github.com/ros2/launch_ros/pull/325#discussion_r979069795

I didn't actually see these being used anywhere else in the standard ROS repositories. But I did find a few places in the documentation: https://github.com/ros2/ros2_documentation/pull/3038

### CODE REVIEW

**Comment by wjwwood** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17370/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11905/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17873/)

**Review by jacobperron — APPROVED** [review]

**Review by ivanpauno — COMMENTED** [review]
Should we deprecate the old names to make the transition easier?
Do we have any linter complaining about this?

**Comment by wjwwood** [comment]
I was going to deprecate in a separate pr, since we could back port this one, but probably only want to deprecate in rolling. I just haven't had time.

**Comment by wjwwood** [comment]
> Do we have any linter complaining about this?

If you're asking about the way the class is named, it's not possible for a linter to know one way or the other... I guess you could say something specific like `*Ros[A-Z].*` should be `ROS` instead. But no we don't have that.

**Comment by clalancette** [comment]
> I was going to deprecate in a separate pr, since we could back port this one, but probably only want to deprecate in rolling. I just haven't had time.

Wait, I'm confused.  If we were to backport this, wouldn't we be breaking compatibility in old distributions?  That is, anything that called `PushRosNamespace` before would now break, right?

**Comment by wjwwood** [comment]
This pr doesn't break API, it just adds new API (well rename and add an alias to the old name). No downstream code is required to change yet.

**Comment by wjwwood** [comment]
I was thinking we could back port it as a convenience for downstream users that want to use the new class name in all branches (or have a single branch for Humble and Rolling and more).

**Review by ivanpauno — APPROVED** [review]

**Pull request merged**
