### PR TITLE
Skip test_node_start test failing with Connext

### PR DESCRIPTION
**Pull request by Blast545**
As the title says, see: https://github.com/ros2/launch_ros/issues/408

### CODE REVIEW

**Comment by Blast545** [comment]
Testing with Iron and Connext Only up-to `launch_testing_ros` to verify that the test is being skipped before running a full CI, see:

[Build Status](https://ci.ros2.org/job/ci_linux/21993/)

**Comment by Blast545** [comment]
Test still enabled in first attempt, trying again with different string:

[Build Status](https://ci.ros2.org/job/ci_linux/21993/)

**Comment by Blast545** [comment]
@clalancette PTAL, @Crola1702 fyi

**Review by fujitatomoya — COMMENTED** [review]
instead of skipping the test, how about backporting https://github.com/ros2/launch_ros/pull/394 to make it robust? test fails with humble too, so fixing the problem would be better to support humble LTS?

**Comment by Blast545** [comment]
@fujitatomoya Are you sure #394 will fix the issue after being backported? Just saw that you opened #420, happy to wait if you are taking a look into it.

**Comment by fujitatomoya** [comment]
yeah i think so, that includes some cosmetic fixes, but main focus was to extend the timeout.

CC: @clalancette

**Comment by clalancette** [comment]
Closing this in favor of #420, which was just merged.

**Pull request closed without merging**
