### PR TITLE
More Helpful Error Messages

### PR DESCRIPTION
**Pull request by DLu**
In place of #268, I catch the yaml error and rethrow as a TypeError, plus add some helpful(?) exception text. 

I added a test case for bad yaml, and a new test function that tests coercing parameters to certain types.

### CODE REVIEW

**Comment by DLu** [comment]
@hidmic ? Any thoughts based on

**Review by adityapande-1995 — APPROVED** [review]

**Comment by adityapande-1995** [comment]
CI : 

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15635/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10315/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13303/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15853/)

**Comment by DLu** [comment]
Thanks @adityapande-1995 

Should I open up PRs for foxy and galactic or is there a magic tool for that?

**Comment by jacobperron** [comment]
We use a bot to help with backports, but I haven't tried it myself. Let's give it a whirl...

**Comment by jacobperron** [comment]
@Mergifyio backport foxy galactic

**Comment by DLu** [comment]
:mage:

**Pull request merged**
