### PR TITLE
[Eloquent Backport] Fix linter by removing unused import

### PR DESCRIPTION
**Pull request by zmichaels11**
Backport of https://github.com/ros2/launch_ros/pull/110#issuecomment-579365342 to Eloquent

### CODE REVIEW

**Comment by zmichaels11** [comment]
@ros2/aws-oncall - please run this CI job
Gist: https://gist.githubusercontent.com/zmichaels11/8741c1927d217368405212c57008d705/raw/d904c2b2da25c464fa387ded9931403cc4c6ea46/ros2.repos
BUILD args: --packages-up-to launch_ros
TEST args: --packages-select launch_ros
Job: ci_launcher

**Comment by zmichaels11** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9164/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4879/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7482/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9084/)

**Comment by dirk-thomas** [comment]
The CI builds are testing the wrong package (`launcH_ros`) and should be checking `ros2launch` instead.

**Comment by zmichaels11** [comment]
Yeah I just caught that. I canceled all the queued tasks and am building with correct parameters

**Comment by zmichaels11** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9165/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4880/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7482/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9084/)

**Comment by dirk-thomas** [comment]
Please hold the merge (even after CI passed). I would like to double check some results from build.ros2.org before...

**Pull request merged**
