### PR TITLE
Fix: typing. Iterable doesn't have __getitem__

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Maybe backport to Humble and Iron

### CODE REVIEW

**Review by adityapande-1995 — COMMENTED** [review]
I'm not sure if CI is failing here due to your changes. Let me run a full CI and check

**Comment by clalancette** [comment]
> I'm not sure if CI is failing here due to your changes. Let me run a full CI and check

There's at least flake8 warnings about `Iterable` that need to be fixed.

**Comment by adityapande-1995** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20348/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14755/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21098/)

**Comment by adityapande-1995** [comment]
Thanks !
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20376/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14785/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21126/)

**Comment by MatthijsBurgh** [comment]
Anything blocking this PR to be merged?

**Comment by clalancette** [comment]
Here's another CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20430/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14832/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21173/)

**Pull request merged**
