### PR TITLE
Fix push-ros-namespace in xml/yaml launch files

### PR DESCRIPTION
**Pull request by ivanpauno**
`expose_action` was missing, and there were no test for markup based launch files.

### CODE REVIEW

**Comment by ivanpauno** [comment]
Should the tag be `push_ros_namespace` or `push-ros-namespace`?
The first one is used in the tutorial https://github.com/ros2/ros2_documentation/blob/master/source/Tutorials/Launch-files-migration-guide.rst. The second option (which I used in this PR), is being used by substitutions (like `find-pkg-share`). We don't have currently a multi-worded action name in launch/launch_ros, exposed to xml/yaml based launch files. I prefer the underscore style (and I don't mind to keep the dash for substitutions).

**Comment by hidmic** [comment]
> Should the tag be `push_ros_namespace` or `push-ros-namespace`?

Well, dashes are much more common in XML, though underscores look nicer in YAML. IMHO this is a valid argument to support tag aliasing. For now, though, I'd go personally and subjectively go with dashes.

**Comment by ivanpauno** [comment]
- Linux [Build Status](https://ci.ros2.org/job/ci_linux/8768/)
- Arch [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/4594/)
- macOS [Build Status](http://ci.ros2.org/job/ci_osx/7163/)
- Windows [Build Status](http://ci.ros2.org/job/ci_windows/8692/)

**Comment by mjcarroll** [comment]
@ivanpauno Can you get this backported please?

**Comment by ivanpauno** [comment]
> @ivanpauno Can you get this backported please?

See https://github.com/ros2/launch_ros/pull/115.

**Pull request merged**
